version: '3'
services:

  db:
    restart: always
    image: postgres:11-alpine
    networks:
      - internal_network
    volumes:
      - ./postgres:/var/lib/postgresql/data

  redis:
    restart: always
    image: redis:5-alpine
    networks:
      - internal_network
    volumes:
      - ./redis:/data

  server:
    build: .
    restart: always
    env_file: .env.production
    command: bash -c "cd web-server; yarn start"
    networks:
      - external_network
      - internal_network
    ports:
      - "127.0.0.1:4000:4000"
    depends_on:
      - db
      - redis
    volumes:
      - ./public/system:/mastodon/public/system

  web:
    build: .
    restart: always
    env_file: .env
    command: yarn start
    networks:
      - external_network
      - internal_network
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - db

networks:
  external_network:
  internal_network:
    internal: true